// flow-typed signature: c0100c52753804a132d56f8b3a83ac35
// flow-typed version: <<STUB>>/babel-plugin-istanbul_v^3.1.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-istanbul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-istanbul/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-istanbul/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-istanbul/lib/index'>;
}
