// flow-typed signature: 4eb5d208354d79a3d940556a6af9cde2
// flow-typed version: <<STUB>>/errio_v1.2.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'errio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'errio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'errio/test/common' {
  declare module.exports: any;
}

declare module 'errio/test/from-object-test' {
  declare module.exports: any;
}

declare module 'errio/test/parse-test' {
  declare module.exports: any;
}

declare module 'errio/test/register-all-test' {
  declare module.exports: any;
}

declare module 'errio/test/register-object-test' {
  declare module.exports: any;
}

declare module 'errio/test/register-test' {
  declare module.exports: any;
}

declare module 'errio/test/set-defaults-test' {
  declare module.exports: any;
}

declare module 'errio/test/stringify-test' {
  declare module.exports: any;
}

declare module 'errio/test/to-object-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'errio/index' {
  declare module.exports: $Exports<'errio'>;
}
declare module 'errio/index.js' {
  declare module.exports: $Exports<'errio'>;
}
declare module 'errio/test/common.js' {
  declare module.exports: $Exports<'errio/test/common'>;
}
declare module 'errio/test/from-object-test.js' {
  declare module.exports: $Exports<'errio/test/from-object-test'>;
}
declare module 'errio/test/parse-test.js' {
  declare module.exports: $Exports<'errio/test/parse-test'>;
}
declare module 'errio/test/register-all-test.js' {
  declare module.exports: $Exports<'errio/test/register-all-test'>;
}
declare module 'errio/test/register-object-test.js' {
  declare module.exports: $Exports<'errio/test/register-object-test'>;
}
declare module 'errio/test/register-test.js' {
  declare module.exports: $Exports<'errio/test/register-test'>;
}
declare module 'errio/test/set-defaults-test.js' {
  declare module.exports: $Exports<'errio/test/set-defaults-test'>;
}
declare module 'errio/test/stringify-test.js' {
  declare module.exports: $Exports<'errio/test/stringify-test'>;
}
declare module 'errio/test/to-object-test.js' {
  declare module.exports: $Exports<'errio/test/to-object-test'>;
}
