// flow-typed signature: 303860c63509cfe42fcccdeeaeae57cd
// flow-typed version: <<STUB>>/fast-json-parse_v1.0.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-json-parse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-json-parse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-json-parse/benchmark' {
  declare module.exports: any;
}

declare module 'fast-json-parse/parse' {
  declare module.exports: any;
}

declare module 'fast-json-parse/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-json-parse/benchmark.js' {
  declare module.exports: $Exports<'fast-json-parse/benchmark'>;
}
declare module 'fast-json-parse/parse.js' {
  declare module.exports: $Exports<'fast-json-parse/parse'>;
}
declare module 'fast-json-parse/test.js' {
  declare module.exports: $Exports<'fast-json-parse/test'>;
}
