// flow-typed signature: 83f6ae4f4d39225768f8f046d786b132
// flow-typed version: <<STUB>>/fast-safe-stringify_v1.1.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-safe-stringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-safe-stringify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-safe-stringify/benchmark' {
  declare module.exports: any;
}

declare module 'fast-safe-stringify/example' {
  declare module.exports: any;
}

declare module 'fast-safe-stringify/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-safe-stringify/benchmark.js' {
  declare module.exports: $Exports<'fast-safe-stringify/benchmark'>;
}
declare module 'fast-safe-stringify/example.js' {
  declare module.exports: $Exports<'fast-safe-stringify/example'>;
}
declare module 'fast-safe-stringify/index' {
  declare module.exports: $Exports<'fast-safe-stringify'>;
}
declare module 'fast-safe-stringify/index.js' {
  declare module.exports: $Exports<'fast-safe-stringify'>;
}
declare module 'fast-safe-stringify/test.js' {
  declare module.exports: $Exports<'fast-safe-stringify/test'>;
}
