// flow-typed signature: 75df635bb2e5b4487d59fa56249b91fc
// flow-typed version: <<STUB>>/heavy_v^4.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heavy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'heavy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heavy/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heavy/lib/index.js' {
  declare module.exports: $Exports<'heavy/lib/index'>;
}
