// flow-typed signature: 65e4e1090e16d721f6ae987641b9b87d
// flow-typed version: <<STUB>>/hoek_v4.1.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hoek'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'hoek' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hoek/lib/escape' {
  declare module.exports: any;
}

declare module 'hoek/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hoek/lib/escape.js' {
  declare module.exports: $Exports<'hoek/lib/escape'>;
}
declare module 'hoek/lib/index.js' {
  declare module.exports: $Exports<'hoek/lib/index'>;
}
