// flow-typed signature: b19a64f19712f68f05e7a3bb6b1e85c9
// flow-typed version: <<STUB>>/items_v2.1.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'items'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'items' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'items/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'items/lib/index.js' {
  declare module.exports: $Exports<'items/lib/index'>;
}
