// flow-typed signature: f30211c9d462cf35749bd92abe0026bf
// flow-typed version: <<STUB>>/pino_v3.0.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pino'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pino' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pino/browser' {
  declare module.exports: any;
}

declare module 'pino/example' {
  declare module.exports: any;
}

declare module 'pino/pino' {
  declare module.exports: any;
}

declare module 'pino/pretty' {
  declare module.exports: any;
}

declare module 'pino/test/addlevel.test' {
  declare module.exports: any;
}

declare module 'pino/test/basic.test' {
  declare module.exports: any;
}

declare module 'pino/test/browser.test' {
  declare module.exports: any;
}

declare module 'pino/test/escaping.test' {
  declare module.exports: any;
}

declare module 'pino/test/extreme.test' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/extreme_child' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/extreme' {
  declare module.exports: any;
}

declare module 'pino/test/helper' {
  declare module.exports: any;
}

declare module 'pino/test/http.test' {
  declare module.exports: any;
}

declare module 'pino/test/levels.test' {
  declare module.exports: any;
}

declare module 'pino/test/pretty.test' {
  declare module.exports: any;
}

declare module 'pino/test/serializers.test' {
  declare module.exports: any;
}

declare module 'pino/test/timestamp.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pino/browser.js' {
  declare module.exports: $Exports<'pino/browser'>;
}
declare module 'pino/example.js' {
  declare module.exports: $Exports<'pino/example'>;
}
declare module 'pino/pino.js' {
  declare module.exports: $Exports<'pino/pino'>;
}
declare module 'pino/pretty.js' {
  declare module.exports: $Exports<'pino/pretty'>;
}
declare module 'pino/test/addlevel.test.js' {
  declare module.exports: $Exports<'pino/test/addlevel.test'>;
}
declare module 'pino/test/basic.test.js' {
  declare module.exports: $Exports<'pino/test/basic.test'>;
}
declare module 'pino/test/browser.test.js' {
  declare module.exports: $Exports<'pino/test/browser.test'>;
}
declare module 'pino/test/escaping.test.js' {
  declare module.exports: $Exports<'pino/test/escaping.test'>;
}
declare module 'pino/test/extreme.test.js' {
  declare module.exports: $Exports<'pino/test/extreme.test'>;
}
declare module 'pino/test/fixtures/extreme_child.js' {
  declare module.exports: $Exports<'pino/test/fixtures/extreme_child'>;
}
declare module 'pino/test/fixtures/extreme.js' {
  declare module.exports: $Exports<'pino/test/fixtures/extreme'>;
}
declare module 'pino/test/helper.js' {
  declare module.exports: $Exports<'pino/test/helper'>;
}
declare module 'pino/test/http.test.js' {
  declare module.exports: $Exports<'pino/test/http.test'>;
}
declare module 'pino/test/levels.test.js' {
  declare module.exports: $Exports<'pino/test/levels.test'>;
}
declare module 'pino/test/pretty.test.js' {
  declare module.exports: $Exports<'pino/test/pretty.test'>;
}
declare module 'pino/test/serializers.test.js' {
  declare module.exports: $Exports<'pino/test/serializers.test'>;
}
declare module 'pino/test/timestamp.test.js' {
  declare module.exports: $Exports<'pino/test/timestamp.test'>;
}
