// flow-typed signature: c0b50bfa8144b4e47447a5d446da7dbc
// flow-typed version: <<STUB>>/super-error_v2.0.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'super-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'super-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'super-error/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'super-error/index' {
  declare module.exports: $Exports<'super-error'>;
}
declare module 'super-error/index.js' {
  declare module.exports: $Exports<'super-error'>;
}
declare module 'super-error/test.js' {
  declare module.exports: $Exports<'super-error/test'>;
}
