// flow-typed signature: c0fc48c7fcc3591d1d1e6971febcb1fb
// flow-typed version: <<STUB>>/tinysonic_v^1.1.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tinysonic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tinysonic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tinysonic/bench' {
  declare module.exports: any;
}

declare module 'tinysonic/example' {
  declare module.exports: any;
}

declare module 'tinysonic/test' {
  declare module.exports: any;
}

declare module 'tinysonic/tinysonic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tinysonic/bench.js' {
  declare module.exports: $Exports<'tinysonic/bench'>;
}
declare module 'tinysonic/example.js' {
  declare module.exports: $Exports<'tinysonic/example'>;
}
declare module 'tinysonic/test.js' {
  declare module.exports: $Exports<'tinysonic/test'>;
}
declare module 'tinysonic/tinysonic.js' {
  declare module.exports: $Exports<'tinysonic/tinysonic'>;
}
